theme: jekyll-theme-minimal
include:
  - README.md
  - folder-structure.md
  - pages.md
  - UIcomp.md
  - ./teacher/pages.md
  - ./teacher/Concept.md
  - ./teacher/Gradescale.md
  - ./teacher/Gradebook.md
  